### ISSUE TITLE
std::source_location in exception messages

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#193]
I think it's time to add `__FILE__`, `__FUNCTION__`, `__LINE__` to all our exception messages.

Also perhaps we can temporarily catch `out_of_range`, append some info on the vars being accessed, and rethrow. I'm getting a little tired of seeing the useless `std::out_of_range, what: map::at` error messages. 

Something like:

```cpp
Error in __FILE__:__FUNCTION__:__LINE__: exception.what(): some extra debug info.
```

**Comment by israel-vieira** [comment]
C++20 provides better support than macros for this purpose, see:
https://en.cppreference.com/w/cpp/utility/source_location for details.

**Comment by jamesturner246** [comment]
Thanks @israel-vieira. That looks more appropriate!
