### ISSUE TITLE
Scrape epi visualisation tool to get datasets in bulk

### ISSUE THREAD

**Issue by dalonsoa** [imperialCHEPI/healthgps#211]

**Comment by alexdewar** [comment]
Message from Ali:

As discussed yesterday, we use the Epi Visualisation Tool (https://vizhub.healthdata.org/epi/) to download remission and fatality rates for Health-GPS. The process is quite manual and laborious as we couldn't find any API to automate it. 

Here are the detailed steps we typically follow to download a single data file:
Click on the "Map" tab on the left.
Choose the Model. (e.g., Diabetes mellitus). 
Select the Measure (e.g., Excess mortality rate).
Select the Year (e.g., 2019).
Select the Age Group. (e.g., 1-4 years).
Select the Sex (e.g., Male).
Click on the "Download" button on the top right.
