### ISSUE TITLE
Initialise weight for population

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#249]
For this change, we will implement weight initialisation for a population.

An `initialise_weight` method will be added to the (for now) `StaticLinearModel` class, and will make use of the shiny new baseline adjustment mechanism `RiskFactorAdjustableModel::adjust_risk_factors(context, vector<Identifier> keys)`.

Here is Ali's C# code for the relevant bits:

```C#
         public void InitializeWeightIndividual(Individual individual)
         {
             double energyintakebaseline = this.baselineMeans[individual.sex][individual.age].GetValue("energyintake");                                                                                                                    

             double eneregyQuantile = individual.energyintake / energyintakebaseline;

             double weightQuantile = GetWeightQuantile(eneregyQuantile, individual.sex);

             double w0 = this.baselineMeans[individual.sex][individual.age].GetValue("weight");

             double weight = w0*weightQuantile;

             individual.weight = weight;
         }   
```
`GetWeightQuantile` is defined:
```C#
         public double GetWeightQuantile(double energyQuantile, string sex)
         {
             double energyPercentile = random.NextDouble();  //GetEnergyPercentile(energyQuantile);
             int index = (int)(energyPercentile * (this.weightQuantiles[sex].Count - 1));

             double result = this.weightQuantiles[sex][index];
             return result;
         }
```

See other functions in e.g. `KevinHallModel`, `StaticLinearModel` to get an idea of how to get/set risk factors from people, and get random numbers. The `keys` value of the baseline adjust call will be a vector containing only `"Weight"_id`, so just pass `{"Weight"_id}`. Happy to help where I can. Unfortunately, I will also be modifying `StaticLinearModel, but I think the merge shouldn't be too painful.

## Update
This issue actually need to be broken down into smaller chunks to be actionable:
- [ ] #251
- [ ] Implement weight initialisation (this issue)

For this to actually work, this will need to be completed after #248 is done.

**Comment by dalonsoa** [comment]
Ali's code (in particular `GetWeightQuantile`) uses `this.weightQuantiles`, which I assume is an attribute of the model defined somewhere. Where can I find this in the C++ code - if anywhere?

**Comment by jamesturner246** [comment]
Sending it via teams
