### ISSUE TITLE
[UMBRELLA] Investigate improper results for some diseases

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#277]
From Jingmin:

Dear James,

Hope this email finds you well. Sorry for this email on the last working day before Christmas. I’m writing to clarify the challenge we are facing with in the Health-GPS model which you might know already.

To begin with, we are using Health-GPS to simulate a synthetic Indian population, estimate changes in their risk factors (e.g. nutrient intake, BMI) over time as a result of policies and thereby changes in population health primarily measured by the incidence and deaths of diseases.

We are evaluating the effect of a tax on HFSS (High in Fat, Salt or Sugar) food in India. Under policy scenarios, people’s consumption of HFSS food is reduced. Therefore, on the one hand, a reduction in sodium intake and BMI is expected, which we’ve already observed in the results. On the other hand, Health-GPS connects sodium, BMI to the diseases by relative risks of sodium and BMI on diseases. So we also expect a reduction in the prevalence of diseases, especially those sodium- and high BMI-relevant diseases.

I’m still struggling with achieving a reduction in the prevalence of diseases. I fail to understand why the reduction in sodium intake was not translated into a reduction in the prevalence of diseases, such as ischemic heart disease and stroke. In addition, the prevalence of diabetes decreases whilst the prevalence of ischemic heart disease does not, even after I added in the data the positive association between diabetes and ischemic heart disease.

I hope it makes sense. Please let me know if you have any questions or need more clarifications somewhere. Thanks a lot!

Merry Christmas and Happy New Year!

Best wishes,
Jingmin

**Comment by jamesturner246** [comment]
Hi Jingmin.

Thanks for that, but probably a little more information will be needed to diagnose this. 

For starters, could you give us an idea of more or less what difference of the noted diseases you are expecting, and could you give some graphs of what you are observing? The exact dataset used. As much detail as you can. 

And can I also confirm that you are indexing the generated data correctly for baseline and intervention, given that it was discovered that recent graphs had improper indexing of results?

**Comment by jamesturner246** [comment]
Thanks @jzhu20. Could you also upload the dataset and config file used to generate these results please?

The instantaneous increase looks like a different issue, so I'll tackle that separately in a new issue.

**Comment by jamesturner246** [comment]
One last thing: could you also send the script used to generate the above plots from the data? Thanks.

**Comment by jzhu20** [comment]
> One last thing: could you also send the script used to generate the above plots from the data? Thanks.

R script and .csv files can be found in this sharefolder.
https://imperiallondon-my.sharepoint.com/:f:/r/personal/jjo11_ic_ac_uk/Documents/CHEPI/research/franco/Health-GPS_SHARED/Health-GPS_INDIA/RESULTS?csf=1&web=1&e=1p5cr7

**Comment by jamesturner246** [comment]
Thanks. I see a number of result directories here; which was the directory for the exact data and config, and script used to generate the above plots? Just So I can fully reproduce your graphs exactly, and have a reference to compare to my end.

**Comment by jzhu20** [comment]
> Thanks. I see a number of result directories here; which was the directory for the exact data and config, and script used to generate the above plots? Just So I can fully reproduce your graphs exactly, and have a reference to compare to my end.

Actually OneDrive is still processing the changes. The folder is in the status of sync pending. That's why you can only see a mess now..

**Comment by jamesturner246** [comment]
Ah, right! Okay, no worries!

**Comment by jzhu20** [comment]
> Thanks @jzhu20. Could you also upload the dataset and config file used to generate these results please?
> 
> The instantaneous increase looks like a different issue, so I'll tackle that separately in a new issue.

India files at HPC are https://imperiallondon-my.sharepoint.com/:u:/r/personal/jjo11_ic_ac_uk/Documents/CHEPI/research/franco/Health-GPS_SHARED/Health-GPS_INDIA/india-files.7z?csf=1&web=1&e=hI9rZu

**Comment by jamesturner246** [comment]
Another important note: from your R script, I see that you are not weighting the values by the `count` field. I would guess that the results would be significantly different if this weighting is taken into account. What happens if you weight the average by count with this data? I'm trying on my end with other data.

**Comment by jzhu20** [comment]
# Updated weighted mean
## Two risk factors - reduction observed as expected
![BMI](https://github.com/imperialCHEPI/healthgps/assets/154426800/a514869b-9bb0-4260-a5c0-d6861daff3f2)
![Sodium](https://github.com/imperialCHEPI/healthgps/assets/154426800/773cd6c0-1351-45f8-9ff5-a2c961ea8d4f)
## Important diseases
### Ischemic heart disease - Issue: Higher prevalence under intervention in 2028-2036, 2040-2055
![IHD](https://github.com/imperialCHEPI/healthgps/assets/154426800/aeb75565-1aae-40c1-ba14-d951500821ba)
### Diabetes
![Diabetes](https://github.com/imperialCHEPI/healthgps/assets/154426800/719093b0-de03-4344-a513-e76cf21cbd98)
### Asthma - Issue: Higher prevalence under intervention from 2043 to 2054
![Asthma](https://github.com/imperialCHEPI/healthgps/assets/154426800/6fe542a1-0511-4d18-847f-fffb8116d02f)
### Ischemic stroke - Issue: Higher prevalence under intervention in 2026-2028, 2034-2055
![Stroke](https://github.com/imperialCHEPI/healthgps/assets/154426800/a97ede81-7c7e-47dd-8c97-bc03b2fd6d18)
### Stomach cancer - Issue: Higher prevalence under intervention in 2036, 2038-2040, 2042, 2046, 2049-2054
![Stomach cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/3a60d0c5-94af-40ec-b3ef-a39d4a6baef4)
### Intracerebral hemorrhage - Issue: Higher prevalence under intervention except in 2055
![Intra hemorrhage](https://github.com/imperialCHEPI/healthgps/assets/154426800/b8f906c4-a85a-4fa4-a40d-6e181cfaabe2)
### Subarachnoid hemorrhage - Issue: Higher prevalence under intervention in 2025-2026, 2033, 2035
![Suba hemorrhage](https://github.com/imperialCHEPI/healthgps/assets/154426800/d9f3cdf3-3f13-43b2-b0c6-41ce48f12006)

**Comment by jamesturner246** [comment]
Thanks Jingmin; they look way better. Now just the disease effect issue to go.

**Comment by jamesturner246** [comment]
A list of priority diseases, for reference.

1. ischemic heart disease
2. diabetes
3. intracerebral hemorrhage
4. ischemic stroke
5. asthma
6. stomach cancer
7. subarachnoid hemorrhage

**Comment by jzhu20** [comment]
I can confirm the scale/unit of sodium in Indian inputs is consistent with that of relative risks in disease data.

**Comment by jamesturner246** [comment]
Thanks Jingmin. How about the second point?

> Further to this, could I also please confirm that the only diseases that are misbehaving are those which depend on sodium?

**Comment by jamesturner246** [comment]
Okay, I've run 50 odd sims in which I've used 'dummy' risk factor models which set factors to constant values, and subtract constant amounts in intervention scenarios. I'm keeping BMI constant in baseline and intervention, but I'm simulating sodium with a constant reduction intervention. We have the results (thanks @jzhu20 for plotting):

![MicrosoftTeams-image](https://github.com/imperialCHEPI/healthgps/assets/6853046/9adf0ed6-a79a-4880-a826-f2ca3dd65b07)

We see, as expected, BMI is constant, Sodium has a constant reduction, and finally a consistent downward trend in prevalence of ischemic heart disease -- this was one of the quote 'problematic' issues from above.

Based on these results, and and the correct behaviour in BMI and Sodium in the Kevinhall model, I'm now moderately convinced that the Kevin Hall and disease code is fine, and the real issue here is either:

1. The disease relative to sodium coefficients are somehow scaled down from what they should be, or
2. That this is, in fact, the actual result all along, and there is less of an effect from sodium as we initially thought

One experiment we should do to really dive deeper is a large parameter sweep. We can use this new dummy model (see #300) to do a large sweep over many BMI and Sodium intervention values, sampled at equally spaced points, with baseline fixed at reasonable constants throughout. And I mean really set these values to their lower and higher extremes, with decent sampling resolution.  We can then plot, say, a heatmap with BMI and sodium on the axes, and cell colour representing mean prevalence of a disease.

Coupled with @jzhu20's India HLM model with Sodium intervention experiment, I think this will give a good picture of how relevant sodium/BMI really are for these diseases. @jzhu20, @jackolney, agree/disagree/thoughts? I'll start preparing it.

**Comment by jamesturner246** [comment]
I'm going to mark this as done, as it appears the issue has been identified and corrected in the latest iteration of simulations.
