### ISSUE TITLE
Model comparison to last version created by Israel

### ISSUE THREAD

**Issue by jackolney** [imperialCHEPI/healthgps#280]
The final version of the model released by Israel ([v1.2.2.0](https://github.com/imperialCHEPI/healthgps/releases/tag/v1.2.2.0)) produced coherent results.

I wonder if a sensible exercise is to run the model in its current state, using the India dataset [or we could revert to the France data], and compare it to a model run using v1.2.2.0 – this may enable us to identify _where_ the model is producing incorrect results.

What does everyone think?

**Comment by jackolney** [comment]
What I am thinking is the following:
- We compare the model v1.2.2.0 to all subsequent changes in sequence.
- i.e. we compare v1.2.2.0 to a committed version in March, then April, May, June etc. and compare outputs.
- We figure out, at what point, a change was committed that caused a significant deviation in results and then do a deep dive into that particular commit, and figure out what in the code changed, whether it is correct and how to rectify it so that results make sense again.

Thoughts?

**Comment by jamesturner246** [comment]
Hi @jackolney. I have been lead to believe that the old model still functions as expected on the French data at least. Though trying it again to be sure, as well as on the India data, should be a priority. 

@jzhu20, would you be able to run a couple of batches of runs with the old model, using the French data for one and the India data for the other? See `./healthgps/example/France.config.json` for a config using the old model. You'd obvs need to change `country_code` for the run batch for India data.

The run traces may not exactly match v1.2.2.0, as the RNG state will be different, given the same initial seed, but the results for the French data using the old model *should* be statistically identical.

**Comment by jackolney** [comment]
Sounds like a sensible plan. Do you think it is worth creating a script to automatically compare the current model against previous versions? I am thinking something that produces figures that will draw two lines – one for the current model and one for a previous version. 

We can then just plug in whatever version of the model we want to compare the current against and produce a quick plot.

**Comment by jamesturner246** [comment]
Also it would be a nice to have this ready to go at any time. Also we wouldn't need to keep running v1.2.2.0 if we save the complete pristine results from this version alongside the plotting script. 

I'd suggest for now we put the script in a directory of https://github.com/imperialCHEPI/healthgps-examples, and keep results from successive versions as further subdirectories, including our 'initial' v1.2.2.0 data. Then we have a continuous record. There are two results data formats generated by a run: the CSV one and the JSON. Depending on how big they are we can keep both. 

It would be useful to look into whether there is information in one format that is not in the other, or if the data is fully redundant. Is so, we can just save one format (the CSV one?).

**Comment by jzhu20** [comment]
## France example - Population fraction of 0.001 - 50 simulations ##

![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/280bc9ab-6194-4d42-b5e0-e166b87d903d)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/f98fda2b-3f68-418e-bb64-647075b212f5)

**Comment by jamesturner246** [comment]
I'm marking this as completed, as we have the confirmation we need (?). Feel free to re-open if needs further investigation.
