### ISSUE TITLE
Null value in nutrients under intervention

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#281]
Null values are found in **_foodcarbohydrate, foodfat, foodprotein, foodsodium, energy intake, weight, bmi_**, under intervention, in some specific years. I'm not sure if it's an issue. For example,
### Female
Null values in 2037, 2039, 2040
### Male
Null values in 2030, 2036, 2050, 2051, 2055
### Female
Null values in 2030, 2036, 2037, 2040, 2043
### Male
Null values in 2028, 2029, 2051

**Comment by jamesturner246** [comment]
Is this from the same simulation as #277?

**Comment by jamesturner246** [comment]
Also, could you give a bit of info about where these NaN are appearing? Are they in the output csv file, or the json file?

Could you upload the file these appear?

**Comment by jzhu20** [comment]
All are based on the same simulation. NaN appeared in output csv files. It can be found in this sharefolder.
https://imperiallondon-my.sharepoint.com/:f:/r/personal/jjo11_ic_ac_uk/Documents/CHEPI/research/franco/Health-GPS_SHARED/Health-GPS_INDIA/Visualization?csf=1&web=1&e=RQOLaa
For example, in HealthGPS_Result_S1.csv, lines 3630, 6056, 6461, etc.

**Comment by jamesturner246** [comment]
Okay. I suggest we make a minimal example which produces these NaN results. Small a population and runtime as possible, with no other cruft to distract us. Can talk about it tomorrow.

**Comment by jzhu20** [comment]
No NaN in France example results.

**Comment by jamesturner246** [comment]
Great, thanks. Need to figure out if it's still happening with India data now.

**Comment by jzhu20** [comment]
No NaN in results with India/France inputs and India diseases data.

**Comment by jamesturner246** [comment]
Ah fantastic, thanks. Can this issue be considered resolved now? Or is there some other permutation of data which is problematic?

**Comment by jzhu20** [comment]
Shall we wait until we get results using the new KH model? There might be problems there.

**Comment by jzhu20** [comment]
I got "nan" in simulation results using KH model. @jamesturner246 
Results can be found here.
https://imperiallondon-my.sharepoint.com/:f:/r/personal/jzhu5_ic_ac_uk/Documents/Project/RSTL_India/Visualization/[Iteration18-India-fulllist](https://imperiallondon-my.sharepoint.com/:f:/r/personal/jzhu5_ic_ac_uk/Documents/Project/RSTL_India/Visualization/Iteration18-India-fulllist?csf=1&web=1&e=r5M0R9)?csf=1&web=1&e=r5M0R9

**Comment by jamesturner246** [comment]
Great, thanks. link is dead. Assume it's still uploading?

**Comment by jamesturner246** [comment]
Thanks @jzhu20. That's better. I'll investigate.

**Comment by jamesturner246** [comment]
Done in https://github.com/imperialCHEPI/healthgps/pull/353 and https://github.com/imperialCHEPI/healthgps/pull/356.
