### ISSUE TITLE
Instantaneous increase observed in more diseases

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#282]
An instant increase is observed in more diseases: 

1. Anxiety in 2039 at baseline;
2. Breast cancer in 2034 at baseline;
3. Colorectal cancer in 2031 and 2050 at intervention, the latter one might be normal;
4. Dermatitis in 2038 at intervention;
5. Liver cancer in 2029 at intervention;
6. Obese weight in 2049 at intervention;
7. Pancreatitis in 2041-2 at intervention.

**Comment by jzhu20** [comment]
![Anxiety](https://github.com/imperialCHEPI/healthgps/assets/154426800/87ef041b-ef53-47f2-aecd-4dceb5fae0fa)
![Breast cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/b6c89a78-8319-4cc0-b08f-53de08898cc3)
![Colorectal cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/24b14bcb-9721-442a-a1e6-6342ded9e55d)
![Dermatitis](https://github.com/imperialCHEPI/healthgps/assets/154426800/63dd7e21-56d6-47f1-bdeb-b1eecfa7905c)
![Liver cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/a232a2a4-4379-4d89-847c-3fe63f3bad83)
![Obesity](https://github.com/imperialCHEPI/healthgps/assets/154426800/a7e52d10-3409-46c8-9667-ddedf19324f8)
![Pancrea](https://github.com/imperialCHEPI/healthgps/assets/154426800/bc428bca-7bf6-44e3-909d-928f11934535)

**Comment by jamesturner246** [comment]
Is this from the same simulation as #277?

**Comment by jzhu20** [comment]
# With updated weighted mean
## Breast cancer - Issue: abnormal decrease before 2030
![Breast cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/d014779c-1ab3-4956-bcc5-fd8ba0f4e996)
## Depression/Esophagus cancer/Gallbladder cancer/Liver cancer/Pancrea cancer/Stomach cancer  - Issue: abnormal faster increase in the first few years/ a big drop in slope
![Depression](https://github.com/imperialCHEPI/healthgps/assets/154426800/de98dcb3-0da2-482e-b597-4fbab2bcbed6)
![Esophagus cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/03cb852c-6414-4b46-a97a-269ab3b41acd)
![Gallbladder cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/1c9c354d-5307-4f38-8c30-33a7182c2e1c)
![Liver cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/f00cbf2c-d155-4e60-ba2c-d6e108ebc6a7)
![Pancrea cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/4b335627-afdf-41bf-9d5c-e0e241f5b270)
![Stomach cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/cdeaad77-e1d9-45f7-b5fd-a5202de225f7)
## Reflux - Issue: abnormal decrease before 2028
![Reflux](https://github.com/imperialCHEPI/healthgps/assets/154426800/ad970c0f-b952-4e09-ad91-44d1ca41621c)
## Thyroid cancer - Issue: abnormal decreasing trend before 2030 and increasing up to 2050 before decreasing again
![Thyroid cancer](https://github.com/imperialCHEPI/healthgps/assets/154426800/1eecaf9f-0bc5-43e6-b865-63c73934d5ed)

**Comment by jamesturner246** [comment]
Thanks. I think in order to determine what is abnormal and what isn't, we should probably get #280 out of the way after we get the India data in #284. Just getting some PBS scripts done.

**Comment by jamesturner246** [comment]
Fixed by #290
