### ISSUE TITLE
Finalise India data and merge into mainline

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#284]
There are a lot of iterations of the India dataset floating around, in varying degrees of completeness/correctness. 

It is time to settle on a 'final' version of the India dataset, and merge this into mainline. Note that we can still add fixes to this in future, but it is less confusing to have a 'single source of truth' which we should all use, unless otherwise noted.

This should hopefully mean that sharing experiments as we debug is a simple matter of sending a relevant JSON file.

The data will be contributed to healthgps in the form of a Github 'pull request'. I'm happy to walk you through the process,

**Comment by jamesturner246** [comment]
Hi @jzhu20. Do you fancy giving this a go and seeing if we can get the India data in today? 

We should dig out the most up-to-date version of the India dataset we have -- I'm guessing there's a copy on the shared drive. Do you have a link to the most recent version? thanks!

**Comment by jzhu20** [comment]
This is the most up-to-date India files with me. https://imperiallondon-my.sharepoint.com/:u:/r/personal/jjo11_ic_ac_uk/Documents/CHEPI/research/franco/Health-GPS_SHARED/Health-GPS_INDIA/india-files.7z?csf=1&web=1&e=I8SXVM
@jamesturner246 When are you available to guide me through it please? Thank you!

**Comment by jamesturner246** [comment]
How's 10:00 tomorrow? Should have enough time to go through the whole GitHub PR process more generally then.
