### ISSUE TITLE
Weight averages in results by `count`

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#290]
See #227

In summary, the averages computed and returned in the resulting CSV files *MUST* be weighted by the `count` field to make any sense. I am seeing significantly different results taking this into account, including a reduction in strange result 'stepping'.

In this issue, the goal is to reproduce and compare some results obtained thus far with `count` weighting taken into account. Happy to chat if you're stuck.

**Comment by jzhu20** [comment]
Updated seven diseases with weighted mean in #277

**Comment by dalonsoa** [comment]
This has been checked, and that was the case, so this issue is no longer required and the only point that remains is to remember to use it. For now, it will be mentioned/included in the solutions included in #285 . In the future it might be useful to mention it in the documentation.
