### ISSUE TITLE
The use of 95% confidence interval in Health-GPS

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#296]
In e.g. data/diseases/diabetes/D250.csv or data/diseases/diabetes/D356.csv file, there are lower and upper values of 95% confidence interval for some measures. How are the lower and upper values used in Health-GPS?
I observed a mess in these confidence intervals, as it may not include mean value in its range, or the upper value is smaller than lower value, etc.

**Comment by jamesturner246** [comment]
Hi @jzhu20. I can confirm that the only columns loaded from these files are as follows:

```cpp
{"age", "gender_id", "measure_id", "measure", "mean"}
```

See https://github.com/imperialCHEPI/healthgps/blob/90af6d86ba72447285d03d6bb6c5c12948645f57/src/HealthGPS.Datastore/datamanager.cpp#L257

Go ahead and close this if no more info is needed.
