### ISSUE TITLE
Run old hierarchical linear model on India data

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#298]
We should compare disease data generated by running the old Hierarchical Linear Model (HLM) on our new India data, to test whether there is something wrong with our new India disease data.

We have already compared the old model on French data on both the latest version of HealthGPS in `main` and version `1.2.2.0` (see #280), and found that disease results are similar, suggesting that nothing has changed in the disease mechanism of the latest HealthGPS. Therefore, if the experiment described in this issue produces the unexpected disease behaviour described in #277, we can be somewhat confident that the issue is in India disease data. 

- [ ] find missing data, if any, needed to run this (e.g. do we need sodium params for the new diseases?)
- [ ] create an India equivalent of the `./healthgps/example/France.Config.json` config
- [ ] simulate and plot disease results for diseases

**Comment by jzhu20** [comment]
### 1. Health-GPS v1.2.2.0 on Indian data ###
#### India.DataFile.csv ####
Issues: SES is missing; different scale of PA; different scale of sodium (easy to rescale); year is missing.
#### India.FactorsMean.Female.csv & India.FactorsMean.Male.csv ####
Issues: different scale of sodium (easy to rescale).
#### JSON files ####
Issue: India.HLM.json and India.EBHLM.json are missing.
@jamesturner246 Can we just use the same parameters in France.HLM.json and France.EBHLM.json files for India simulation?
#### Notes: It should be safe to add parameters of sodium later since new diseases are also attributed to BMI. ####


### 2. New Health-GPS on French data ###
Issues:  No weight available in French data, only BMI; no data of new diseases.

**Comment by jamesturner246** [comment]
For the JSON files, I *believe* they are generated from the dataset using the tools at https://github.com/imperialCHEPI/healthgps-tools. They require Windows to run. Maybe we can have a look at regenerating those for the India data tomorrow.

Is the SES data easy to acquire?

**Comment by jzhu20** [comment]
## Both using main branch (new version) ##
### French inputs and Indian disease data ###
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/c8a1f855-ae25-45a1-955d-569580840c58)
### Indian inputs (but French parameters in HLM and EBHLM) and Indian disease data ###
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/654c42c5-1702-472c-aef7-1d9881135b81)

**Comment by jamesturner246** [comment]
Nice work! This is a good start. :+1: 

Now we can alter the existing intervention a bit in the main config file to have e.g. an instantaneous reduction in sodium, and see if we get the same unexpected results for diseases we get with the new model. Looking forward to seeing this.

**Comment by jzhu20** [comment]
## Main branch - HLM model ##
### French inputs - Indian disease - "food-labelling" intervention ###
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/48a80975-e411-4e0c-8cb5-c71a2920e12b)
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/c6dfbe2f-e4ce-47ff-8cd1-c831f89f9215)
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/1142ce0c-7520-45e1-86df-ebb06d4be062)

![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/96f8b81a-7af2-4cea-97a6-4d36223d485a)

![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/a52bd658-4b72-4de7-89d1-dcb9778ca8e3)
#### Findings ####
1. Significant reductions in BMI and obesity
2. Comparing data:
- Ischemic heart diseases: consistent lower prevalence under intervention, range: 7.8e-07-4.6e-04
- Ischemic stroke: consistent lower prevalence under intervention, range: 3.1e-06-1.0e-04
- Asthma: consistent lower prevalence under intervention, range: 4.2e-05-7.1e-04
- Diabetes: consistent lower prevalence under intervention, range: 3.4e-05-2.4e-03
- Intracerebral hemorrhage: mostly lower prevalence under intervention, except in 2023, 2024, 2026, range of reduction: 2.1e-06-5.8e-05
- Subarachnoid hemorrhage: mostly lower prevalence under intervention, except in 2023, range of reduction: 5.1e-07-1.2e-05 
- Stomach cancer: mostly lower prevalence under intervention, except in 2028, 2042, range of reduction: 5.3e-07-1.1e-05
Notes: consistent higher sodium consumption under intervention
3. Cancer results are more unstable

**Comment by jzhu20** [comment]
> Nice work! This is a good start. 👍
> 
> Now we can alter the existing intervention a bit in the main config file to have e.g. an instantaneous reduction in sodium, and see if we get the same unexpected results for diseases we get with the new model.

The interventions in old HLM are on BMI/energy. A reduction in sodium is hard in this old version of Health-GPS.

**Comment by jamesturner246** [comment]
Humm.. Doesn't it work if you change the `"impacts"` in the `"interventions"` section of the main config?

Like in the `"simple"` intervention, you have:

```json
 129                     "impacts": [                                                                                  
 130                         {                                                                                         
 131                             "risk_factor": "BMI",                                                                 
 132                             "impact_value": -1.0,                                                                 
 133                             "from_age": 0,                                                                        
 134                             "to_age": null                                                                        
 135                         }                                                                                         
 136                     ]   
 ```

but replace "BMI" with Sodium, or add it to the impacts list?

```json
                     "impacts": [                                                                                  
                         {                                                                                         
                             "risk_factor": "BMI",                                                                 
                             "impact_value": -1.0,                                                                 
                             "from_age": 0,                                                                        
                             "to_age": null                                                                        
                         },
                         {
                             "risk_factor": "Sodium",
                             ...                                                                                         
                     ]   
```

For example?

**Comment by jzhu20** [comment]
## Main branch - HLM model ##
### Indian inputs - Indian disease - "food-labelling" intervention - 50 simulations ###


![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/1ce1aff6-6026-4975-8c16-7f77c5d7924d)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/d73d6694-8ec9-4f90-adb2-530c009325e2)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/6b3a26bf-27ad-416c-8f28-fdd11c7b4ec6)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/d28e2c2c-032b-45e3-ae48-c19295e90d83)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/2e609a4d-8c7a-4589-817a-1f76a2fbc5d6)

#### Comparing data ####

1. Ischemic heart diseases: consistent increase under intervention, range: -2.736e-04, -1.701e-05
2. Ischemic stroke: mostly increase under intervention
3. Asthma: consistent reduction under intervention, range: 2.037e-05, 2.677e-04
4. Diabetes: consistent reduction under intervention, range: 6.398e-06, 8.155e-04
5. Intracerebral hemorrhage: consistent increase under intervention, range of reduction: -5.900e-06, -7.212e-05
6. Subarachnoid hemorrhage: mostly increase under intervention
7. Stomach cancer: mostly reduction under intervention, except in 8 years

Notes: consistent reduction in bmi; reduction in sodium in 2037-2047
