### ISSUE TITLE
Run new Kevin Hall model on French data

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#299]
We should run the new Kevin Hall model on French data, to ensure that it behaves sensibly with alternative data.

We will need new data: at minimum, the French equivalent of all the India data inside `./healthgps/example_new`, including a French equivalent of `./healthgps/example_new/Config.json`.

- [ ] is the required French data readily available? locate it if not
- [ ] new `Config.json` for France, using the new model
- [ ] Run simulations and pot disease results.

**Comment by jzhu20** [comment]
### New Health-GPS with KH model on French data ###
Issues: 

- Weight and height are missing, only BMI;

- Income is missing;

- Sector is missing;
- Carbohydrate is missing;
- Different scale of PA;
- Data of new diseases are missing.

**Comment by jamesturner246** [comment]
While BMI is okay to compute, the others might be more of a pain to get, right? Maybe let's focus on #298, and see how far we get with that instead.

**Comment by jamesturner246** [comment]
Closed as resolved.
