### ISSUE TITLE
Add a 'dummy' model type for constant risk factors

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#300]
For this task, we will create a new 'dummy' risk factor model `RiskFactorDummyModel`, which will simply assign a given set of risk factors to some configurable constant value (perhaps mean by age and gender).

This will allow us to isolate the disease mechanism entirely (see #277) and, hopefully, will greatly speed up the diagnosis of unexpected disease behaviour for our 'minimal example' debug configurations, and eventually facilitate easier unit tests for risk factor models -- this dummy model can be considered a 'mock' risk factor model.

**Comment by jzhu20** [comment]
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/c9440a24-84c2-4a3b-a123-79806bc835d9)
