### ISSUE TITLE
Create template for India report

### ISSUE THREAD

**Issue by jackolney** [imperialCHEPI/healthgps#301]

**Comment by jackolney** [comment]
- Develop template in CHEPI style
- Set out headings
- Write intro
- Methods
- Results
- Discussion

**Comment by jzhu20** [comment]
A manuscript for The Lancet Global Health has been agreed. Template is standard. https://www.thelancet.com/pb/assets/raw/Lancet/authors/tlgh-info-for-authors.pdf
