### ISSUE TITLE
Identify outputs to be generated for India report

### ISSUE THREAD

**Issue by jackolney** [imperialCHEPI/healthgps#302]
Two subtasks in this issue:

- [ ] Confirm current outputs
- [ ] Identify what additional outputs are needed

**Comment by jzhu20** [comment]
Based on my conversation with @jamesturner246 on Teams, in the current outputs,

1. Nutrient intake, physical activity, energy intake are averages by age, gender, year and source.
2. BMI, height and weight are averages by age, gender, year and source.
3. Diseases are prevalence by age, gender, year and source.

To be confirmed,

1. disability_weight **?**
2. deaths **?**
3. migrations **?**
4. normal_weight, over_weight, obese_weight, above_weight are prevalence(percentage) by age, gender, year and source. **?**
5. yll, yld, daly are sum in each group by  age, gender, year and source. **?**

**Comment by jzhu20** [comment]
Maxime's summary based on a group meeting

Main results:
Figure 1. Trends in BMI and sodium 2023-2052, by income group, baseline vs. each scenario
Table 1. Absolute and relative changes compared to baseline for disease incidence (top 10-15 main diseases) and associated government healthcare expenditure at 30 years, by scenario [Adding the totals among all diseases at the bottom of the table]
Figure 2. Trends in YLL and DALYs 2023-2052, by income group, baseline vs. each scenario

Appendix:
Table A1. Full list of changes in disease incidence (all), by income group, by scenario
Figure A1. Trends in disease incidence (aggregating by disease group, e.g., CVD, diabetes) 2023-2052, by income group, by scenario

For later, three other points we discussed this morning (needed for the submission to the journal but not urgent for the RTSL meeting):
-	Confidence intervals in all Health-GPS results (for all tables and figures listed above). Two strategies (a. first-best, to try first but may lead to very high confidence intervals; b. second-best):
a.	using the minimum and maximum from the various runs obtained from Health GPS for each outcome, year, and income group
b.	using the lower- and upper-bound policy effect estimates provided by Maxime; to do so we would just need to run Health-GPS 3 times for each scenario and use the difference in outcomes between the lower- and upper-bound as confidence interval
-	Appendix C in the paper draft should include data sources used in Health-GPS modelling for this study, i.e., population estimates, weight/height, physical activity, relative risks, healthcare expenditure, etc.
-	By the time we submit the paper to the journal, we must have published an updated detailed Appendix explaining Health-GPS functioning on the Health-GPS website (to cite it).
