### ISSUE TITLE
Run simulations to generate robust outputs for India report

### ISSUE THREAD

**Issue by jackolney** [imperialCHEPI/healthgps#303]
Following #335

**Comment by jzhu20** [comment]
## main_hslope branch - 1% population - 39 of 50 simulations - ps1 ##
### Difference in risk factors under intervention compared to baseline ###

![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/86799b47-0da2-419c-9499-173e906dfc1c)
### Difference in prevalence number under intervention compared to baseline ###




![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/230dcf01-552b-4b1d-99c9-4183cb9127d6)



### Difference and cumulative difference in incidence number under intervention compared to baseline ###


![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/0958cba8-cd6e-46f5-befe-61789400def8)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/a90971d2-976e-418f-84a8-0325f74ac648)

### Difference and cumulative difference in YLD, YLL, DALY ###



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/ddc64407-4f2b-4e0b-92d9-4e9614e7fd59)

**Comment by jzhu20** [comment]
## main_hslope branch - 1% population - 37 simulations - ps2 ##
### Difference in risk factors under intervention compared to baseline ###




![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/d5228ebf-9099-451d-b56f-0ab260550c09)




### Difference in prevalence number under intervention compared to baseline ###


![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/2639029c-c1d0-4f9a-b4dc-a72f282eb9b7)







### Difference and cumulative difference in incidence number under intervention compared to baseline ###




![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/c22e0fd4-7b73-4d26-b871-18f696712ab4)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/ec6f375c-45a2-4419-ae0f-1e50715b7261)



### Difference and cumulative difference in YLD, YLL, DALY ###




![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/63acf2d7-4306-4dba-bd39-3fd8194db4d5)





### Period life expectancy ###




![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/af3deaf8-88df-42eb-abc3-6d60fd1a469d)
