### ISSUE TITLE
Construct an estimate of intervention disease reduction

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#308]
In order to test whether disease prevalence in intervention really is 'incorrect', we should form our own estimates from first principles. We know the equation for new disease probability (below), and we know the relative risk coefficients.

```
P_disease = incidence * (mean_risk_current / mean_risk_initial)
```

We need to set up a simulation and find:
- [ ] the mean combined risk for a disease in our starting population
- [ ] the mean combined risk for that disease at one or more future points of interest
- [ ] our estimate of probability of disease, using the equation above, the mean risk values and existing incidence data
- [ ] the actual simulated incidence of that disease at these points of interest

**Comment by jzhu20** [comment]
### Estimate of adjusted incidence rate based on IHME epidemiological data  ###
### Simulated incidence rate (income group 1 - 500 simulations) ###
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jzhu5/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jzhu5/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


  | Estimate | Simulated
-- | -- | --
Min | 0.000 | 0.000
1st Q | 0.000 | 0.0002135
Median | 0.002 | 0.0034862
Mean | 0.014 | 0.0094834
3rd Q | 0.029 | 0.0203051
Max | 0.059 | 0.0399933



</body>

</html>

**Comment by jzhu20** [comment]
### Simulated and expected incidence rates of seven diseases ### 
### Note: Interaction with other diseases is not considered in expected incidence rate. ###
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jzhu5/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jzhu5/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


IHD | Simulated incidence rate | Expected incidence rate based on IHME 2019   data and risk factors
-- | -- | --
Min | 0.0000 | 0.0000
1st Q | 0.0002135 | 0.0002
Median | 0.0034862 | 0.0058
Mean | 0.0094834 | 0.0142
3rd Q | 0.0203051 | 0.0274
Max | 0.0399933 | 0.0586
SD | 0.0102 | 0.0163
  |   |  
ASTHMA | Simulated | Expected
Min | 0.0000 | 0.0017
1st Q | 0.002443 | 0.0027
Median | 0.004368 | 0.0048
Mean | 0.004685 | 0.0052
3rd Q | 0.006636 | 0.0073
Max | 0.018766 | 0.0186
SD | 0.00248 | 0.00271
  |   |  
DB | Simulated | Expected
Min | 0.0000 | 0.0000
1st Q | 0.0005226 | 0.0005
Median | 0.0026306 | 0.0031
Mean | 0.0032480 | 0.0040
3rd Q | 0.0057776 | 0.0073
Max | 0.0086643 | 0.0102
SD | 0.00279 | 0.00354
  |   |  
STROKE | Simulated | Expected
Min | 0.0000 | 0.0001
1st Q | 0.0001034 | 0.0001
Median | 0.0005041 | 0.0006
Mean | 0.0015739 | 0.0017
3rd Q | 0.0022943 | 0.0024
Max | 0.0096364 | 0.0077
SD | 0.00203 | 0.00217
  |   |  
INTRA | Simulated | Expected
Min | 0.0000 | 0.0000
1st Q | 0.00004594 | 0.0000
Median | 0.0005319 | 0.0006
Mean | 0.0008710 | 0.0009
3rd Q | 0.001398 | 0.0014
Max | 0.00425 | 0.0033
SD | 0.000957 | 0.000961
  |   |  
SUBA | Simulated | Expected
Min | 0.0000 | 0.0000
1st Q | 0.00002619 | 0.0000
Median | 0.0001408 | 0.0001
Mean | 0.0001601 | 0.0002
3rd Q | 0.0002185 | 0.0002
Max | 0.001091 | 0.0006
SD | 0.000153 | 0.000145
  |   |  
STOMACH CANCER | Simulated | Expected
Min | 0.0000 | 0.0000
1st Q | 0.000009612 | 0.0000
Median | 0.0001138 | 0.0001
Mean | 0.0002017 | 0.0002
3rd Q | 0.0003979 | 0.0004
Max | 0.001029 | 0.0006
SD | 0.000208 | 0.000189



</body>

</html>

**Comment by jamesturner246** [comment]
This is fantastic. Nice one. Many thanks @jzhu20.

**Comment by jamesturner246** [comment]
I'm closing this, as I'm under he impression that it is now resolved. Reopen if not.
