### ISSUE TITLE
Run old hierarchical linear model with sodium reduction

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#309]
Following up #298, alter the existing intervention a bit in the main config file to have e.g. an instantaneous reduction in sodium, and see if we get the same unexpected results for diseases we get with the new model.

**Comment by jamesturner246** [comment]
Okay. A big reduction in sodium clearly shows our desired reduction in IHD, which further supports that the disease mechanism is working as expected, relative to risk factors. I'm pretty convinced at this point.

We need to double check the scale of the sodium risk coefficients (#310), and form our own estimates for disease probability (as in #308).

**Comment by jzhu20** [comment]
## Update - with all RR of sodium corrected ##


![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/7d9af143-3288-45f9-ab22-f48929b54cff)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/0a807b39-8f71-479a-b211-d96d8cfa91cc)

**Comment by jzhu20** [comment]
Notes of correcting relative risks of sodium, e.g.:
in data/diseases/ischemicheartdisease/relative_risk/risk_factor/female_ischemicheartdisease_sodium.csv and
data/diseases/ischemicheartdisease/relative_risk/risk_factor/male_ischemicheartdisease_sodium.csv,
rescale the first row of sodium intake from in mg to g, i.e. change 2000 to 2, change 4325.6 to 4.3256, change 6651.2 to 6.6512.
