### ISSUE TITLE
Run dummy model on other new diseases

### ISSUE THREAD

**Issue by jamesturner246** [imperialCHEPI/healthgps#320]
Similarly to #300, we should run the dummy model with exaggerated risk factor intervention values on the other new diseases to check those as well. IHD behaves as expected, as in #300, but IHD is not diagnosed as 'problematic'. Some other diseases which are 'problematic' are as follows:

* ischemicstroke
* subarachnoidhaemorrhage
* intercerebralhaemorrhage
* stomachcancer

Run the dummy model on these with exaggerated intervention, as in #300.

**Comment by jzhu20** [comment]
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/31dd30e0-aa81-42f9-9ac2-811d2367e45a)

**Comment by jamesturner246** [comment]
Ah yes, thanks for that!
