### ISSUE TITLE
Test RR of sodium/BMI in Kevin Hall model

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#321]
Following up #311, a series of tests on the relative risks of sodium/BMI on seven important diseases:

- [ ] Remove RR data of BMI only since it's strange
- [ ] Remove RR data of sodium + monotonic RR data of BMI
- [ ] Remove RR data of BMI + exaggerate RR of sodium

**Comment by jzhu20** [comment]
## No BMI, big RR of sodium - 100 simulations ##


![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/c9297328-95bf-4963-8d69-30387522af12)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/a87781c1-4860-4d2f-825c-521366e6c57a)

**Comment by jamesturner246** [comment]
Hi @jzhu20. Just wanted to double check: the sodium relative risk for all of these diseases have al been adjusted to grams, right?

**Comment by jzhu20** [comment]
> Hi @jzhu20. Just wanted to double check: the sodium relative risk for all of these diseases have al been adjusted to grams, right?

No. We keep using milligrams in KH model version. RR is also in milligrams.

**Comment by jamesturner246** [comment]
Oh yeah, sorry. Getting muddled up...

**Comment by jzhu20** [comment]
## No sodium - increasing RR of BMI ##
![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/9e97a0c8-9973-43b1-bdfe-6d4baea7d8a0)



![Image](https://github.com/imperialCHEPI/healthgps/assets/154426800/a6daf51d-64c4-4716-a7ac-8559ace4e207)
