### ISSUE TITLE
Generate outcomes by income group

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#324]
Outcomes include
risk factors - sodium, BMI
disease - prevalence and incidence for each disease
burden of disease - yll, yld, daly

**Comment by jamesturner246** [comment]
As a temporary solution, it was agreed that three simulations could be run for the three different income groups, with all other parameters being equal. 

The population is initialised with the same income class, newborns should also be assigned to that income class, but each individual is allowed to move to a different income class at adulthood. So the only people with a different income class should be those that reached adulthood and were reassigned. 

One disadvantage to this approach is that it does not consider adults that are reassigned to this class, but were of another class in childhood.

These three experiments will require a hack to `StaticLinearModel`.

**Comment by jamesturner246** [comment]
***IN FUTURE*** try different dsets in `./data` for each income group, with diffreent population distributions.
