### ISSUE TITLE
Update RR of BMI on new diseases

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#329]
List of diseases:
Ischemic heart disease
Ischemic stroke
Intracerebral hemorrhage
Subarachnoid hemorrhage

**Comment by jamesturner246** [comment]
Continuing from #319 .

**Comment by jzhu20** [comment]
References:
[DOI: 10.1093/aje/kwi166](https://doi.org/10.1093/aje/kwi166)
https://doi.org/10.3390/nu13072343
