### ISSUE TITLE
Commit changes in datastore

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#341]
Commit changes in Config files and Data to main_hslope and hack_income_class_hslope branches respectively.

**Comment by jzhu20** [comment]
Changes are merged to branches main_hslope and main_hslope_threads in #344 .

**Comment by jamesturner246** [comment]
I guess these will need to be added to `hack_income_class` as well. Just noting this to remind us.

**Comment by jzhu20** [comment]
https://github.com/imperialCHEPI/healthgps/pull/345

**Comment by jamesturner246** [comment]
Fixed in #345
