### ISSUE TITLE
Bounds in nutrients

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#349]
Update bounds in nutrient intake, without filtering outliers.

**Comment by jzhu20** [comment]
Min and max values of these four nutrients are

- Carbohydrate: 22.09977, 1979.988
- Fat: 1.093948, 561.4858
- Protein: 3.649882, 309.119
- Sodium: 9.986686, 45379.46

**Comment by jamesturner246** [comment]
Wow, they're considerably wider. Thanks -- I'll merge them in.
