### ISSUE TITLE
Remove unnecessary checks in `DataManager`

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#401]
The `DataManager` class's methods contain a lot of code that looks like this:

```c++
std::vector<PopulationItem>
DataManager::get_population(const Country &country,
                            std::function<bool(unsigned int)> time_filter) const {
    auto results = std::vector<PopulationItem>();

    if (index_.contains("demographic")) {
        // [snip]
        } else {
            notify_warning(
                fmt::format("{} population file: '{}' not found.", country.name, filename));
        }
    } else {
        notify_warning("index has no 'demographic' entry.");
    }

    return results;
}
```

Now that we're checking the input file with a schema, we know that the index file will contain a `demographic` property, so this check is unnecessary. The only thing is that the current code would seem to suggest that this property is optional rather than required, though really I think it *should* be required. And we should def be throwing an error if the file can't be read!

@jamesturner246 Are you ok with me removing all these unnecessary checks?

**Comment by jamesturner246** [comment]
Purge them. For the emperor!

**Comment by alexdewar** [comment]
Cool, I'll do that then.

Unfortunately I've just realised that the schema isn't enforcing the presence of these fields though: #403 

I suppose I should fix that first!
