### ISSUE TITLE
Remove unnecessary threads from `EventMonitor`

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#408]
It seems odd to me that there are threads whose only role is to hang around waiting for data from other threads, then passing it on again. I *think* we could just remove them and pass the data directly between the relevant threads, cutting out the middleman.

**Comment by alexdewar** [comment]
After digging into this a bit, it seems that it's perhaps not as simple as I first thought. While some of the actions that are performed in response to events being received are simply print statements, some of them involve writing to an output file and moving this to the simulation thread *could* introduce latency from the IO (IO performance on the HPC can be pretty crummy).

@israel-vieira I'm wondering if you could shed some light on why you initially added separate threads for handling events? Was it because benchmarks showed latency for the IO operations or was it just a design choice from the offset?

**Comment by israel-vieira** [comment]
This separation was a design decision to decouple the simulation running from the results processing. At moment there is only a Json file writer, but one can easily plug an in-memory processor or output to different format, e.g. Csv, parquet, streaming, etc. 

There is also a performance aspect, initially the IO was inside the simulation thread but the runtime  was unpredictable, for the same scenario, huge variations for no reason. It was also producing two files per experiment, one from each simulation: baseline and intervention.

@alexdewar I hope this answers your question.

**Comment by alexdewar** [comment]
Thanks, Israel. That's useful to know.

**Comment by alexdewar** [comment]
Following @israel-vieira's explanation, I think this isn't the right approach so I'll close this for now
