### ISSUE TITLE
Move processing of all input files into same module

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#418]
Currently the code for reading the static data lives in `HealthGPS.Datastore` while, for some reason, the code for reading model config files is in `HealthGPS.Console`. In order to implement #406, we will want to reuse some of the infrastructure in `HealthGPS.Datastore`, at which point it seems more logical to just have all of the input file parsing in the same place.

It would make more sense to have everything in one module, but `HealthGPS.Datastore` doesn't seem like the right name. @jamesturner246 Do you have any name preferences? We could go with `HealthGPS.InputFiles` or something.

**Comment by jamesturner246** [comment]
Other than the highly imaginative `Dataloader`, not really sure... Any mindblowing ideas?

**Comment by alexdewar** [comment]
How about:

1. `HealthGPS.Input`
2. `HealthGPS.InputFiles`
3. `HealthGPS.Config`
4. `HealthGPS.InputData`

I'm sure there are more :laughing:. Any preference?

**Comment by jamesturner246** [comment]
`Input` seems most concise. :+1:
