### ISSUE TITLE
`clang-tidy`: Suppress `misc-include-cleaner`

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#432]
The
[`misc-include-cleaner`](https://clang.llvm.org/extra/clang-tidy/checks/misc/include-cleaner.html)
warning points out any places where types, functions etc. are being used without the
relevant headers being *directly* included in the source file. While this might sound
like a good idea in principle, in practice it means that there are an absurd number of
warnings being generated for the code base and every PR from now on will likely have a
few more. The benefit seems dubious so let's just disable it.

**Comment by jamesturner246** [comment]
Might be worth eventually opening a PR to do the required steps though. I'm often confused by unused imports or where something is imported from and how indirectly. For now we can disable it, but let's make an issue to go through it properly later.

**Comment by alexdewar** [comment]
We can do, but the only thing is it's likely to flag up things on new PRs and we'll only notice once the bot has reviewed it.  If we do want to enable it, we might want to use it in combination with [this pre-commit hook](https://github.com/pocc/pre-commit-hooks) which runs [`include-what-you-use`](https://github.com/include-what-you-use/include-what-you-use)
