### ISSUE TITLE
Make zip caching code robust to race conditions

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#454]
Currently, we extract zip files to a cache folder, whose path is based on a hash of the zip file. The problem is that if another instance of HealthGPS is started while extraction is taking place, it may attempt to read the data while extraction is partway through.

This might sound unlikely, but it could definitely happen with multiple jobs running on the HPC simultaneously, as the same cache folder will be being used for each.

I think the right solution is to extract the zip file to a temporary folder (in the same parent folder as the destination folder) and then rename it once extraction is complete, which I think should be an atomic operation.

**Comment by jamesturner246** [comment]
Maybe a bit of a pedantic point, but isn't renaming a non-atomic copy if temp and cache are on different devices? 

The reason I ask is that `$TMPDIR` points to a node-local scratch space during a job (which is used by `std::filesystem::temp_directory_path` -- [see Notes section](https://en.cppreference.com/w/cpp/filesystem/temp_directory_path)), whereas the cache dir is in `$HOME`.

Presumably these moves will not actually be atomic. On Imperial HPC, at least.

**Comment by alexdewar** [comment]
Not pedantic at all! It kind of needs to be atomic, otherwise things will still be broken.

What I was thinking was we could make a temporary folder *in the same place* as the destination folder, e.g. if your destination is `my_dir` you'd first do the extraction to `my_dir.tmp` (or `my_dir.some_random_number`), then rename it, which I think *should* be atomic: https://stackoverflow.com/questions/7054844/is-rename-atomic

**Comment by jamesturner246** [comment]
Ahhh yes, ... that makes sense. Yes, thanks for explaining. :+1:
