### ISSUE TITLE
Forbid additional properties in data index files

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#486]
See: https://github.com/imperialCHEPI/healthgps/pull/404

I initially tried setting `additionalProperties` to false everywhere in the schema, but it broke validation so I didn't bother. I should have opened an issue at the time though, because we do also want to prevent users from adding additional properties (at least most of the time). In part this just makes the files cleaner, but it also prevents users from changing non-existent properties that won't actually do anything (including if they misspell the name of an actual property).

**Comment by jamesturner246** [comment]
> but it also prevents users from changing non-existent properties that won't actually do anything (including if they misspell the name of an actual property).

Precisely the cause of the last fiasco. We probably want to be as pedantic as we can get away with here. :+1:

**Comment by alexdewar** [comment]
Oh dear. Was that with the static data or the config files?

**Comment by jamesturner246** [comment]
That was the static relative disease risk files, in that case.
