### ISSUE TITLE
[BUG] Children's BMI extremely high

### ISSUE THREAD

**Issue by jzhu20** [imperialCHEPI/healthgps#522]
## Describe the bug

After adding time trend, children's BMI is extremely high.

## To Reproduce

1. Using config files '...'
2. Use command '...'
3. See issue '...' inside output files/text '...'

## Expected behavior

Children's BMI within a normal range. After introducing time trend to nutrients and energy intake, children's expected weight should be adjusted with a different equation from adults.
The correct equation is
`expected_weight_adjusted = weight_in_factors_mean * (expected_energy_intake_with_time_trend / expected_energy_intake_in_factors_mean)^0.45`

## Software versions

- OS: HPC
- Health-GPS commit hash 282a6140f9c6b6cdf6e83a9a09de28bccadd4ed0

## Additional context

NA

**Comment by jamesturner246** [comment]
In the `"Weight"` branch of `KevinHallModel::get_expected`:

- [ ] branch if `age >= kevin_hall_age_min`, containing existing equation
- [ ] branch else, containing child equation above.

Note that this means that the expected values for weight and energy intake in the FactorsMean files are still *required*.
