### ISSUE TITLE
[BUG] Zip files are corrupted on download on Windows

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#536]
## Describe the bug

When downloading a static data file on Windows, the file is always corrupted (the checksum doesn't match). On examining the downloaded file, I found that CRs had been inserted before every LF 🙃.

I'm digging into it now.

## To Reproduce

Run HGPS using any of the examples on Windows.

## Software versions

- OS: Windows 10

**Comment by jamesturner246** [comment]
Uh oh!
