### ISSUE TITLE
[OSB] Suggestion: Technical documentation should be in main branch

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#71]
It makes sense logically to have these changes in the same place as the code; often if you change some aspect of the code you will also need to make a change to the documentation and it makes sense to do this in a single commit.

You could get GitHub to use your ``/docs`` folder for documentation to start with. This will require a bit more tweaking if/when you implement #69 and want to include documentation generated by e.g. Doxygen.

**Comment by israel-vieira** [comment]
In general, this is very bad idea, documentation must be able quick to change and evolve independent of code.

Mixing technical documentation and code will require fake code compilation, CI running and version numbers to be generated for the sack of simply updating the documentation. Furthermore, documentation is not check by the compiler, can be written by different people, not necessarily code developers, and gains nothing from the code development lifecycle.

**Comment by alexdewar** [comment]
This is partly just a matter of personal taste, which is why I put "suggestion" in the title. I don't think it's wrong to do it the way you have. Just because your documentation is in the main branch doesn't mean it can't evolve quickly or that it has to be tied to a specific release of the code, any more than it does if it lives in the `gh-pages` branch, though.

A (very) common approach is to have the source files for the documentation in the main branch and then have the CI system automatically build it (with `jekyll` or whatever) and push the generated HTML to `gh-pages`. The advantage of this, as I said, is that it *can* make it easier to keep the docs in sync with the code (e.g. if you're searching for something in your code to change, then any instances of it in the docs will also show up in the results of `git grep` or whatever). It also makes it easier to auto-publish the latest version of your API documentation; you just get the CI system to run `doxygen` while it's at it and push the output of that too.
