### ISSUE TITLE
[OSB] Prefer ``std::unordered_map`` to its ordered counterpart

### ISSUE THREAD

**Issue by alexdewar** [imperialCHEPI/healthgps#77]
The code base appears to make fairly heavy use of ``std::map``s (I found 218 uses) and much less use of ``std::unordered_map``s (``n=35``). While ``std::map`` has its place, it is *much* slower than ``std::unordered_map`` for common operations: https://www.geeksforgeeks.org/map-vs-unordered_map-c/

The advantage that ``std::map`` offers is that the data structure is always sorted by key. However, depending on the algorithm that one is using, this is often not necessary, so ``std::unordered_map`` should be preferred. And if you have a tight loop that does a lot of lookups, the difference in performance can be very substantial. Even for the case where you want the *result* of an algorithm to be sorted by key, you do have the option of sorting the keys after performing the computation (e.g. do your calculations using ``std::unordered_map`` then convert to a ``std::map`` for printing the result to the terminal).

For data structures that are hardly used the performance benefit will be negligible, however, given that there are so many uses of ``std::map`` I suspect there are some places where performance could be improved by swapping in a ``std::unordered_map``.

The same goes for ``std::set`` vs ``std::unordered_set``.

Side note: Many of the uses of ``std::map`` seem to use a ``std::string`` as the key. While this is a very common use of ``std::map``s, there will be a greater computational cost to hashing a string than to using, say, an ``int`` as the key, so this may be another place where optimisations are to be found. Of course, if you can do away with a map entirely and replace it with a ``std::vector`` performance will be better still.

All of these suggestions though may involve a trade-off between convenience and performance, so it's only worth making these sorts of changes in critical code paths.

**Comment by jamesturner246** [comment]
This is more or less done, and the remaining ones were more troublesome if I recall. 
Closing
